[workspace]
members = ["nipa-macros", "nipa-traits"]

[package]
name = "hello-nipa"
version = "0.1.0"
edition = "2021"

[dependencies]
nipa-macros = { path = "./nipa-macros" }
nipa-traits = { path = "./nipa-traits" }
